### ISSUE TITLE
Split library into TestRunner and UnitTest libraries?

### ISSUE THREAD

**Issue by RogerChristopher** [RedRockControls/SimpleUnitTestLibrary#3]
At the moment I usually define the unit tests for a library in another PLC in the library to keep the dependancies of the library being tested to a minimum, but this means they are not accesible to an external test project.

Iit would be good to be able to define the tests in the library itself, but without necessarily including the test runner and visualisation in the library. This would allow a client project to run tests defined in a library it uses. 

This would require the test runner to be defined in one library and the unit test base class (and supporting functions) to be defined in another library. The library under test then has a reference to the UnitTest library and the test project has a reference to the TestRunner library

Good idea or too complicated?

**Comment by mark-lazarides** [comment]
I am not too worried about testing the library from within the library itself, especially if I have access to the test project, so I can see where and how it was tested or recreate for myseld.

**Comment by RogerChristopher** [comment]
No, but I do want the tests to live as close to the code being tested as possible, so when the code gets modified, the tests can change with it (i.e follow the versioning). Having the tests in another PLC or project hurts this, but I don't want the test runner in the library being tested (too many dependancies).

**Comment by mark-lazarides** [comment]
I agree they should live as close as possible, but I think your original approach to testing is still the correct. The whole library workflow is made difficult by the TwinCAT tooling.

By placing one half of the test architecture as a dependancy of the lib, you are placing a forward constraint on the project that tests those anyway.

I imagine the majority of users will still want to test in-project, mainly because I don't think that many people bother with library development. I also imagine that the majority of TC users need a bit of time to get used to this whole idea, let alone managing several libraries required to make it work.

If it were split, the TestRunner lib will always require the unittest lib as a reference.  Do you think marking the unittest lib as "Publish all IEC symbols" in the TestRunner lib project would be a good halfway house? Then there are two routes for people using these. "Advanced" users can use the UnitTest lib where they want, then use the TestRunner lib to run them. anyone else can just install the TestRunner and use as per the existing?

**Comment by RogerChristopher** [comment]
Yes, good idea - I think this would work. Could you force the UnitTestLib to use the same namespace as the TestRunner lib? Otherwise, you would need to qualify all refs to things in the UnitTestLib with its namespace (I think) if you are accessing them via the TestRunner lib. Need to just try it, I suppose.

**Comment by RogerChristopher** [comment]
UnitTestBase is now in its own library (tcl_UnitTestBaseClasses) so tests can be defined without needing a reference to tcl_SimpleUnitTestLibrary, and I have added a TestSuite class to hold related tests. tcl_BaseClasses uses this library to define its tests in the library now (rather than a separate plc project) - the plc project has a reference to tclSimpleUnitTestLibrary and just runs the tests now.

tclSimpleUnitTestLibrary has a definition for TUnitTestbase and TTestSuite so the library can be used as before without needing to know about the tcl_UnitTestBaseClasses library

tcl_SimpleUnitTest_ExampleProject shows both usages.

**Comment by RogerChristopher** [comment]
On balance, its not worth the complexity overhead, so I will merge the two libraries.
